"""
Django settings for chatwave project.

Generated by 'django-admin startproject' using Django 5.2.7.

Для документации: https://docs.djangoproject.com/en/5.2/topics/settings/
"""

import os
from pathlib import Path

# ===== Пути =====
BASE_DIR = Path(__file__).resolve().parent.parent

# ===== Быстрый старт =====
SECRET_KEY = os.environ.get("SECRET_KEY", "fallback-secret-key")
DEBUG = True
ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost").split(",")

# ===== Приложения =====
INSTALLED_APPS = [
    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Проект
    'mychat.apps.MychatConfig',
    'myauth.apps.MyauthConfig',

    # Channels
    'channels',
]

# ===== Middleware =====
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Наш middleware для last_seen
    'myauth.middleware.UpdateLastSeenMiddleware',
]

# ===== URL =====
ROOT_URLCONF = 'chatwave.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # Если будут глобальные шаблоны, добавим путь
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',  # нужен для request в шаблонах
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ===== ASGI/WSGI =====
WSGI_APPLICATION = 'chatwave.wsgi.application'
ASGI_APPLICATION = 'chatwave.asgi.application'  # Для Channels

# ===== База данных =====
DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DATABASE_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.environ.get('DATABASE_NAME', 'chatwave_db'),
        'USER': os.environ.get('DATABASE_USER', 'chatuser'),
        'PASSWORD': os.environ.get('DATABASE_PASSWORD', 'chatpass'),
        'HOST': os.environ.get('DATABASE_HOST', 'db'),
        'PORT': os.environ.get('DATABASE_PORT', '5432'),
    }
}

# ===== Валидация пароля =====
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# ===== Локализация =====
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ===== Статика =====
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "mychat" / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"  # Для collectstatic (production)

# ===== Медиа =====
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'  # Для хранения видео сообщений

# ===== Авторизация =====
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/chat/room_list/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# ===== Default primary key =====
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ===== Channels (WebSocket) =====
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": os.environ.get("CHANNEL_LAYERS_BACKEND", "channels_redis.core.RedisChannelLayer"),
        "CONFIG": {
            "hosts": [os.environ.get("REDIS_URL", "redis://redis:6379/0")]
        },
    },
}


DATA_UPLOAD_MAX_MEMORY_SIZE = 52_428_800   # 50 MB (лимит для form POST)
FILE_UPLOAD_MAX_MEMORY_SIZE = 52_428_800

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file_info': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/info.log'),
            'formatter': 'verbose',
        },
        'file_error': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/error.log'),
            'formatter': 'verbose',
        },
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file_error'],
            'level': 'INFO',
            'propagate': True,
        },
        'mychat': {
            'handlers': ['console', 'file_info', 'file_error'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

