# Generated by Django 5.2.7 on 2025-10-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychat', '0003_alter_userprofile_last_seen_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='chat_videos/'),
        ),
    ]
