# Generated by Django 5.2.7 on 2025-10-11 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychat', '0004_message_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
