# Generated by Django 5.2.7 on 2025-10-11 20:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychat', '0005_chatroom_allowed_users_chatroom_is_locked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='accessible_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
