# Generated by Django 5.2.7 on 2025-10-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychat', '0007_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
    ]
