# Generated by Django 5.2.7 on 2025-10-25 19:45

import mychat.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychat', '0008_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/', validators=[mychat.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='message',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='chat_videos/', validators=[mychat.validators.validate_file_size]),
        ),
    ]
